# Site settings
title: WEBBAB
email: info@webbab.se
url: https://webbab.se
description: "Hemsidor, animerade film, och mycket mer till företag. Vi bygger professionella, responsiva webbsidor till ett mer fördelaktigt pris. Vi bygger lösningar efter dina behov."

# Color settings (hex-codes or rgba)
color:
  primary: '#960051'
  primary-rgba: 'rgba(150,0,80,0.75)'
  primary-dark: '#14050f'
  primary-light: '#f7f7f7'
  secondary-light: '#ededed'
  links: '#960051'

# Footer settings (copyright name)
footer: Webbyrån WEBBAB

# Social networks usernames. fontawesome code and url.
social:
  - title: Facebook
    fa: facebook-official
    url: https://facebook.com/webbab.se
  - title: Vimeo
    fa: vimeo-square
    url: https://vimeo.com/webbab
  - title: YouTube
    fa: youtube-play
    url: https://youtube.com/webbab
  - title: LinkedIn
    fa: linkedin-square
    url: https://linkedin.com/company/webbab

# Medarbetare
medarbetare:
  - namn: Johan Lindberg
    titel: Grundare, Kundansvarig
    text: Lorem ipsum dolor sit amet, qui in soluta integre dissentiunt, ne primis eligendi antiopam eum. Ex dicta tibique duo. Sit epicurei electram definiebas at, eum ut veniam deserunt.
    img: johan.png
    tel: 026-456 17 11
    email: johan@webbab.se
  - namn: Mattis Johansson
    titel: Projektledare
    text: Lorem ipsum dolor sit amet, qui in soluta integre dissentiunt, ne primis eligendi antiopam eum. Ex dicta tibique duo. Sit epicurei electram definiebas at, eum ut veniam deserunt.
    img: mattis.png
    tel: 026-456 17 12
    email: mattis@webbab.se


# Build settings
markdown: kramdown
permalink: /portfolio/:title #pretty
